# Generated by Django 3.2.5 on 2023-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='adress_model',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес модели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='adress_nastroiki',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес настройки'),
            preserve_default=False,
        ),
    ]
