# Generated by Django 3.2.5 on 2023-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20230913_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='token',
            new_name='chat_id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='id_tg',
        ),
        migrations.AddField(
            model_name='camera',
            name='object_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID объектов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='adress_model',
            field=models.FileField(upload_to='', verbose_name='Адресс модел'),
        ),
        migrations.AlterField(
            model_name='model',
            name='adress_nastroiki',
            field=models.FileField(upload_to='', verbose_name='Адресс настроеки'),
        ),
    ]
