# Generated by Django 3.2.5 on 2023-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20230916_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
