# Generated by Django 3.2.5 on 2023-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='company name'),
        ),
    ]
