# Generated by Django 3.2.5 on 2023-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='bio',
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='логин'),
        ),
    ]
